spring:
  application:
    name: simple-config-server
  cloud:
    config:
      server:
        git:
          uri: ${simple-config-files-location}
server:
  port: 8888
management:
  security:
    enabled: false
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
